module.exports = [
    "Kansas City",
    "Philadelphia",
    "Denver",
    "Buffalo",
    "Detroit",
    "Dallas",
    "San Francisco",
    "Cincinnati",
    "Minnesota",
    "Jacksonville",
    "Seattle",
    "Miami",
    "LA Chargers",
    "Las Vegas",
    "Green Bay",
    "Atlanta",
    "New England",
    "Cleveland",
    "NY Giants",
    "Carolina",
    "Baltimore",
    "Arizona",
    "New Orleans",
    "Chicago",
    "Washington",
    "Tampa Bay",
    "Pittsburgh",
    "LA Rams",
    "Tennessee",
    "NY Jets",
    "Indianapolis",
    "Houston",
  ];